export const HANDLE_CHANGES = 'HANDLE_CHANGES';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_LOADING = 'REGISTER_LOADING';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//----------------------->

export const SEND_MESSAGE_LOADING = 'SEND_MESSAGE_LOADING';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const HANDLE_SCHEDULE_CHANGE = 'HANDLE_SCHEDULE_CHANGE';
export const HANDLE_BODY_CHANGE = 'HANDLE_BODY_CHANGE';
export const HANDLE_MESSAGE_CHANGES = 'HANDLE_MESSAGE_CHANGES';

export const GET_MESSAGE_LOADING = 'GET_MESSAGE_LOADING';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_FAILED = 'GET_MESSAGE_FAILED';

export const GET_SCHEDULE_LOADING = 'GET_SCHEDULE_LOADING';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_MSCHEDULE_FAILED = 'GET_MSCHEDULE_FAILED';

export const ADD_SCHEDULE_LOADING = 'ADD_SCHEDULE_LOADING';
export const ADD_SCHEDULE_SUCCESS = 'ADD_SCHEDULE_SUCCESS';
export const ADD_SCHEDULE_FAILED = 'ADD_SCHEDULE_FAILED';

export const DELETE_SCHEDULE_LOADING = 'DELETE_SCHEDULE_LOADING';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_FAILED = 'DELETE_SCHEDULE_FAILED';

export const POPULATE_SCHEDULE = 'POPULATE_SCHEDULE';

export const UPDATE_SCHEDULE_LOADING = 'UPDATE_SCHEDULE_LOADING';
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULEE_SUCCESS';
export const UPDATE_SCHEDULE_FAILED = 'UPDATE_SCHEDULE_FAILED';

export const GET_REGIONS_LOADING = 'GET_REGIONS_LOADING';
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS';
export const GET_REGIONS_FAILED = 'GET_REGIONS_LOADING';
